# Generated by Django 5.0.7 on 2024-08-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomatoimage',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
